spring.application.name=demo
camunda.client.mode=saas
camunda.client.auth.client-id=yw6XTQQffnCAbk7gvvzKhl7IftqE3_qr
camunda.client.auth.client-secret=rnfaA16h60-92Wq-xHu~wxRZ~WBLiii55cJH0RU_2woTkzimkxar53X60.rtw8V0
camunda.client.cloud.cluster-id=73727d45-f91d-4a67-a7db-5571c09fa57f
camunda.client.cloud.region=bru-2

